import Head from "next/head";
import { getLayout } from "@/components/layout/Layout";
import axios from "axios";
import styled from "styled-components";
import React from "react";
import { Character } from "@/components/character/Character";
import { ApiResponse, CharacterType, Episode } from "@/assets/types/types";
import { GetStaticProps } from "next";

export const getStaticPaths = async () => {
  const charactersRes = await axios.get<ApiResponse<CharacterType>>(`https://rickandmortyapi.com/api/character`);
  const paths = charactersRes.data.results.map((el) => {
    return { params: { id: String(el.id) } };
  });

  return {
    paths,
    fallback: "blocking", // false or "blocking"
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const { id } = params || {};

  const characterRes = await axios.get<CharacterType>(`https://rickandmortyapi.com/api/character/${id}`);
  //

  const episodes = await Promise.all(
    characterRes.data.episode.map((el) => {
      return axios.get<string[]>(el).then((res) => res.data);
    })
  );

  if (!characterRes || !episodes.length) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      character: characterRes.data,
      episodes: episodes,
    },
  };
};

type Props = {
  character: CharacterType;
  episodes: Episode[];
};
export default function Characters({ character, episodes }: Props) {
  if (!character) {
    return <h1>No characters</h1>;
  }
  return (
    <>
      <Head>
        <title>Character</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Character character={character} episodes={episodes} />
      </Main>
    </>
  );
}
Characters.getLayout = getLayout;

const Main = styled.main`
  margin-top: 30px;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
`;
