import Head from "next/head";
import { getLayout } from "@/components/layout/Layout";
import axios from "axios";
import styled from "styled-components";
import React from "react";
import { Character } from "@/components/character/Character";
import { ApiResponse, CharacterType } from "@/assets/types/types";
import Link from "next/link";

export const getStaticProps = async () => {
  const charactersRes = await axios.get<ApiResponse<CharacterType>>("https://rickandmortyapi.com/api/character");
  return {
    props: {
      characters: charactersRes.data.results,
    },
  };
};

type Props = {
  characters: CharacterType[];
};
export default function Characters({ characters }: Props) {
  if (!characters) {
    return <h1>No characters</h1>;
  }

  return (
    <>
      <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        {characters.map((character) => {
          return (
            <StyledLink key={character.id} href={`characters/${character.id}`}>
              <Character character={character} />
            </StyledLink>
          );
        })}
      </Main>
    </>
  );
}
Characters.getLayout = getLayout;

export const Main = styled.div`
  margin-top: 30px;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 20px;
`;
const StyledLink = styled(Link)`
  all: inherit;
  cursor: pointer;
`;
